# Generated by Django 3.2 on 2021-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20210409_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
